language: r
cache: packages
latex: false
pandoc: false
fortran: false

matrix:
  include:
    - dist: xenial
    - os: osx
      brew_packages: qpdf
      env: EXTERNAL_QPDF=true
    - os: osx
    - os: osx
      osx_image: xcode7.3
      before_install: sed -i.bak 's/-isysroot /-I/g' $(R RHOME)/etc/Makeconf
